language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
  
dist: trusty
      
branches:
  only:
    - master
    - cran
    - /^hotfix\/.*$/
    - /^release\/.*$/

r_packages:
  - covr
  - Hmisc

after_success:
  - Rscript -e 'library(covr); codecov()'
